# Generated by Django 4.2.11 on 2025-12-23 05:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('name', models.CharField(blank=True, max_length=50, null=True, verbose_name='이름')),
                ('username', models.CharField(error_messages={'unique': '이미 사용 중인 아이디입니다.'}, max_length=150, unique=True, validators=[django.core.validators.RegexValidator(message='아이디는 영문 소문자와 숫자만 사용 가능합니다.', regex='^[a-z0-9]+$')], verbose_name='아이디')),
                ('height', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.1, message='키를 올바르게 설정해주세요')], verbose_name='키')),
                ('current_weight', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.1, message='몸무게를 올바르게 설정해주세요.')], verbose_name='현재 체중')),
                ('target_weight', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.1, message='목표 체중을 올바르게 설정해 주세요.')], verbose_name='목표 체중')),
                ('muscle_mass', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0, message='근육량을 올바르게 설정해주세요.')], verbose_name='골격근량')),
                ('body_fat', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0, message='체지방률을 올바르게 설정해주세요')], verbose_name='체지방률')),
                ('age', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1, message='나이를 올바르게 설정해주세요.')], verbose_name='나이')),
                ('gender', models.CharField(choices=[('M', '남'), ('F', '여')], default='M', max_length=10, verbose_name='성별')),
                ('allergies', models.TextField(blank=True, null=True, verbose_name='알레르기 정보')),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
