# Generated by Django 4.2.11 on 2025-12-23 06:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='age',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1, message='나이는 1살 이상부터 입력할 수 있어요.'), django.core.validators.MaxValueValidator(150, message='나이가 너무 많게 입력되었어요. 다시 확인해 줄래요?')], verbose_name='나이'),
        ),
        migrations.AlterField(
            model_name='user',
            name='body_fat',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0, message='체지방률이 마이너스일 수는 없겠죠?'), django.core.validators.MaxValueValidator(100.0, message='체지방률은 100%를 넘을 수 없어요.')], verbose_name='체지방률'),
        ),
        migrations.AlterField(
            model_name='user',
            name='current_weight',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.1, message='몸무게는 0보다 커야 정확한 계산이 가능해요.'), django.core.validators.MaxValueValidator(500.0, message='몸무게 수치가 너무 커요. 다시 확인해 줄래요?')], verbose_name='현재 체중'),
        ),
        migrations.AlterField(
            model_name='user',
            name='height',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.1, message='키가 너무 작게 입력되었어요. 다시 확인해 줄래요?'), django.core.validators.MaxValueValidator(300.0, message='키가 너무 크게 입력되었어요. 다시 확인해 줄래요?')], verbose_name='키'),
        ),
        migrations.AlterField(
            model_name='user',
            name='muscle_mass',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0, message='근육량은 음수로 입력할 수 없어요.'), django.core.validators.MaxValueValidator(200.0, message='근육량 수치가 너무 높아요. 다시 확인해 줄래요?')], verbose_name='골격근량'),
        ),
        migrations.AlterField(
            model_name='user',
            name='target_weight',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.1, message='목표 체중을 올바르게 설정해 주세요.'), django.core.validators.MaxValueValidator(500.0, message='목표 수치가 너무 높아요. 다시 확인해 줄래요?')], verbose_name='목표 체중'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(error_messages={'unique': '이미 누가 사용 중인 아이디네요! 다른 걸로 골라보시겠어요?'}, max_length=150, unique=True, validators=[django.core.validators.RegexValidator(message='아이디는 영문 소문자와 숫자만 사용 가능해요. 대문자는 쓸 수 없어요.', regex='^[a-z0-9]+$')], verbose_name='아이디'),
        ),
    ]
