# Generated by Django 4.2.11 on 2025-12-23 07:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_age_alter_user_body_fat_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='current_weight',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.1, message='몸무게는 0보다 커야 정확한 계산이 가능해요.'), django.core.validators.MaxValueValidator(300.0, message='몸무게 수치가 너무 커요. 다시 확인해 줄래요?')], verbose_name='현재 체중'),
        ),
        migrations.AlterField(
            model_name='user',
            name='muscle_mass',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0, message='근육량은 음수로 입력할 수 없어요.'), django.core.validators.MaxValueValidator(100.0, message='근육량 수치가 너무 높아요. 다시 확인해 줄래요?')], verbose_name='골격근량'),
        ),
        migrations.AlterField(
            model_name='user',
            name='target_weight',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.1, message='목표 체중을 올바르게 설정해 주세요.'), django.core.validators.MaxValueValidator(300.0, message='목표 수치가 너무 높아요. 다시 확인해 줄래요?')], verbose_name='목표 체중'),
        ),
    ]
