# Generated by Django 5.2.8 on 2025-11-25 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(max_length=150, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('first_name', models.CharField(blank=True, max_length=30)),
                ('last_name', models.CharField(blank=True, max_length=30)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('height', models.FloatField(blank=True, help_text='신체 키 (cm)', null=True)),
                ('current_weight', models.FloatField(blank=True, help_text='현재 몸무게 (kg)', null=True)),
                ('target_weight', models.FloatField(blank=True, help_text='목표 몸무게 (kg)', null=True)),
                ('muscle_mass', models.FloatField(blank=True, help_text='근육량 (kg)', null=True)),
                ('body_fat', models.FloatField(blank=True, help_text='체지방률 (%)', null=True)),
                ('age', models.IntegerField(blank=True, help_text='나이', null=True)),
                ('gender', models.CharField(choices=[('M', '남'), ('F', '여')], default='M', max_length=10)),
                ('nickname', models.CharField(blank=True, max_length=30, null=True)),
                ('allergies', models.TextField(blank=True, help_text='알레르기 정보 (쉼표로 구분)', null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
