# Generated by Django 5.2.8 on 2025-11-25 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='age',
            field=models.IntegerField(blank=True, help_text='나이', null=True, verbose_name='나이'),
        ),
        migrations.AlterField(
            model_name='user',
            name='allergies',
            field=models.TextField(blank=True, help_text='알레르기 정보 (쉼표로 구분)', null=True, verbose_name='알레르기 정보'),
        ),
        migrations.AlterField(
            model_name='user',
            name='body_fat',
            field=models.FloatField(blank=True, help_text='체지방률 (%)', null=True, verbose_name='체지방률'),
        ),
        migrations.AlterField(
            model_name='user',
            name='current_weight',
            field=models.FloatField(blank=True, help_text='현재 몸무게 (kg)', null=True, verbose_name='현재 몸무게'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='이메일'),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, max_length=30, verbose_name='이름'),
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('M', '남'), ('F', '여')], default='M', max_length=10, verbose_name='성별'),
        ),
        migrations.AlterField(
            model_name='user',
            name='height',
            field=models.FloatField(blank=True, help_text='신체 키 (cm)', null=True, verbose_name='키'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='활성화 여부'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_staff',
            field=models.BooleanField(default=False, verbose_name='직원 여부'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(blank=True, max_length=30, verbose_name='성'),
        ),
        migrations.AlterField(
            model_name='user',
            name='muscle_mass',
            field=models.FloatField(blank=True, help_text='근육량 (kg)', null=True, verbose_name='근육량'),
        ),
        migrations.AlterField(
            model_name='user',
            name='nickname',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='닉네임'),
        ),
        migrations.AlterField(
            model_name='user',
            name='target_weight',
            field=models.FloatField(blank=True, help_text='목표 몸무게 (kg)', null=True, verbose_name='목표 몸무게'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=150, unique=True, verbose_name='아이디'),
        ),
    ]
