# Generated by Django 4.2.11 on 2025-12-19 04:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CommunityPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('RESTAURANT', '식당 추천'), ('REVIEW', '변화 후기'), ('QNA', 'Q&A')], max_length=20)),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='community_posts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RestaurantRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('restaurant_name', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=100)),
                ('recommended_menu', models.CharField(max_length=100)),
                ('health_tag', models.CharField(choices=[('HIGH_PROTEIN', '고단백'), ('LOW_FAT', '저지방'), ('BALANCED', '균형식'), ('DIET', '다이어트'), ('OUT', '외식')], max_length=20)),
                ('post', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='restaurant_info', to='community.communitypost')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_answered', models.BooleanField(default=False)),
                ('post', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='question_info', to='community.communitypost')),
            ],
        ),
        migrations.CreateModel(
            name='ChangeReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.CharField(choices=[('1W', '1주'), ('2W', '2주'), ('1M', '1개월')], max_length=2)),
                ('change_type', models.CharField(choices=[('WEIGHT', '체중 변화'), ('DIET', '식습관 변화'), ('EXERCISE', '운동 습관')], max_length=20)),
                ('weight_diff', models.FloatField(blank=True, help_text='체중 변화 (kg, 감소는 음수)', null=True)),
                ('post', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='review_info', to='community.communitypost')),
            ],
        ),
        migrations.CreateModel(
            name='PostLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='community.communitypost')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'post')},
            },
        ),
    ]
