# Generated by Django 4.2.11 on 2025-12-19 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0002_postcomment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='communitypost',
            name='category',
            field=models.CharField(choices=[('RESTAURANT', '식당 추천'), ('REVIEW', '변화 후기'), ('QNA', 'Q&A'), ('FREE', '잡담')], max_length=20),
        ),
    ]
