# Generated by Django 4.2.11 on 2025-12-23 00:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('calorie', models.IntegerField()),
                ('carbohydrate', models.IntegerField()),
                ('protein', models.IntegerField()),
                ('fat', models.IntegerField()),
                ('sugar', models.IntegerField()),
                ('fiber', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.IntegerField()),
                ('meal_time', models.CharField(max_length=10)),
                ('restaurant', models.CharField(max_length=100)),
                ('course_type', models.CharField(max_length=10)),
                ('meal_name', models.CharField(max_length=200)),
                ('subMenuTxt', models.TextField(blank=True, null=True)),
                ('p_score', models.IntegerField(default=0)),
                ('photoUrl', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserSelectedMeal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selected_at', models.DateTimeField(auto_now_add=True)),
                ('meal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meal.meal')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DinnerRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.IntegerField()),
                ('ai_menu_name', models.CharField(blank=True, max_length=255, null=True)),
                ('ai_reason_text', models.TextField(blank=True, null=True)),
                ('ai_response_json', models.TextField(blank=True, null=True)),
                ('p_score', models.FloatField(default=0)),
                ('is_eaten', models.BooleanField(default=None, help_text='None: 미선택 / True: 먹음 / False: 안 먹음', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('user_selected_meal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dinner_recommendations', to='meal.userselectedmeal')),
            ],
        ),
        migrations.CreateModel(
            name='MealFood',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_main', models.BooleanField()),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meal.food')),
                ('meal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meal.meal')),
            ],
            options={
                'unique_together': {('meal', 'food')},
            },
        ),
        migrations.AddConstraint(
            model_name='dinnerrecommendation',
            constraint=models.UniqueConstraint(fields=('user', 'date'), name='unique_dinner_per_lunch'),
        ),
    ]
