# Generated by Django 4.2.11 on 2025-12-18 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='meal',
            name='photoUrl',
            field=models.URLField(blank=True, null=True),
        ),
    ]
