# Generated by Django 4.2.11 on 2025-12-16 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("meal", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="meal",
            name="photoUrl",
            field=models.TextField(blank=True, null=True),
        ),
    ]
