# Generated by Django 6.0 on 2025-12-10 07:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='meal',
            name='p_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='meal',
            name='subMenuTxt',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='DinnerRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ai_menu_name', models.CharField(blank=True, max_length=255, null=True)),
                ('ai_reason_text', models.TextField(blank=True, null=True)),
                ('ai_response_json', models.TextField(blank=True, null=True)),
                ('p_score', models.FloatField(default=0)),
                ('selected_lunch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meal.meal')),
            ],
        ),
        migrations.CreateModel(
            name='UserSelectedMeal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selected_at', models.DateTimeField(auto_now_add=True)),
                ('meal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meal.meal')),
            ],
        ),
    ]
