# Generated by Django 4.2.11 on 2025-12-24 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='weightchangeprediction',
            name='estimated_weight',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
